import { defaultModalityFor, type GeneratedTechnique } from '@reps/core';
import type { AiProvider } from './types';

const TECHNIQUE_TITLES = [
  'Warm up routine',
  'Core movement',
  'Consistency drill',
  'Speed and control',
  'Fixing common mistakes',
  'Put it together',
];

function fakeTechnique(skill: string, title: string, index: number): GeneratedTechnique {
  return {
    title,
    whyItMatters: `This is a stand-in technique for ${skill}, used when no model key is configured.`,
    modality: defaultModalityFor('motor'),
    practicePrompt: `Practise ${title.toLowerCase()} for 10 focused repetitions.`,
    estimatedMinutes: 10 + index,
    searchQueries: [`${skill} ${title.toLowerCase()} beginner`],
  };
}

/**
 * Deterministic provider used for tests and for running the API with no keys.
 * Output satisfies the same schemas as a real model, so the pipeline is
 * exercised end to end rather than stubbed out.
 */
export function createFakeAiProvider(): AiProvider {
  return {
    name: 'fake',

    async suggestOnboarding(skill) {
      return {
        archetype: 'motor',
        goals: [
          { label: `Play your first ${skill} piece`, description: 'A single finishable outcome.' },
          { label: 'Perform for a friend', description: 'Good enough to show someone else.' },
          { label: 'Practise without stopping', description: 'Sustained, unbroken execution.' },
        ],
        levels: [
          { label: 'I have never tried', description: 'Starting from nothing at all.' },
          { label: 'I know the basics', description: 'I can do simple things, slowly.' },
          { label: 'I am inconsistent', description: 'Some days it works, some days it does not.' },
        ],
      };
    },

    async generatePath(input) {
      return {
        archetype: 'motor',
        techniques: TECHNIQUE_TITLES.map((title, index) =>
          fakeTechnique(input.skill, title, index),
        ),
      };
    },

    async regenerateTail(input) {
      return Array.from({ length: input.count }, (_unused, index) =>
        fakeTechnique(input.context.skill, `Alternative route ${index + 1}`, index),
      );
    },

    async generateBridge(input) {
      return fakeTechnique(input.context.skill, 'Easier first step', 0);
    },

    async rankResources(input) {
      return {
        selections: input.candidates.slice(0, 2).map((candidate) => ({
          candidateId: candidate.id,
          reason: 'Chosen by the fake provider, which always takes the first candidates.',
        })),
      };
    },

    async generateContent(input) {
      if (input.format === 'flashcards') {
        return {
          format: 'flashcards',
          cards: Array.from({ length: 5 }, (_unused, index) => ({
            front: `Fake prompt ${index + 1} for ${input.technique.title}`,
            back: `Fake answer ${index + 1}.`,
          })),
        };
      }

      if (input.format === 'drill') {
        return {
          format: 'drill',
          steps: [
            `Set a timer for ${input.context.dailyMinutes} minutes.`,
            input.technique.practicePrompt,
            'Stop early if quality drops.',
          ],
          durationMinutes: Math.min(input.context.dailyMinutes, 60),
          successCriteria: 'You completed the reps without the quality dropping off.',
        };
      }

      return {
        format: 'ai_lesson',
        title: input.technique.title,
        body: `This is placeholder lesson content for **${input.technique.title}**, generated by the fake provider so the application can run without any model API keys configured.`,
        keyPoints: ['This content is a placeholder.', 'Configure a provider key for real lessons.'],
      };
    },
  };
}
